### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by lucyewright** [fac-15/DRINKIO#32]
your submit button has a name attribute with no value. you also have a value attribute with a value... were you debating which one to use?
<img width="459" alt="screenshot 2018-11-23 at 10 14 53" src="https://user-images.githubusercontent.com/40594944/48938273-a877cb00-ef08-11e8-88dc-dcd5f766be89.png">

**Comment by Whooolia** [comment]
It was old version - updated in master branch
