### ISSUE TITLE
What happens when your server returns no beers?

### ISSUE THREAD

**Issue by denis-gosweat** [fac-15/DRINKIO#50]
If no beers are matched the frontend console shows an error. In the xhr response you need to check that at lease 1 beer has actually been returned. If there is an empty array you could do some more DOM goodness and pop a box out of somewhere saying that no beers could be found.

![image](https://user-images.githubusercontent.com/44803580/48939646-d3641e00-ef0c-11e8-923a-e2710ad30f0a.png)

This code is master rather than the staging branch:
https://github.com/fac-15/DRINKIO/blob/715739fcf19634e351bcd5c7f4f3fba3b63e67fa/public/dom.js#L20-L24

**Comment by Oliversw** [comment]
Thanks! Added some small error handling styling to the page
