### ISSUE TITLE
SO MANY BEERS!

### ISSUE THREAD

**Issue by lucyewright** [fac-15/DRINKIO#51]
why are there so many of the same beer in your drop down menu!?
<img width="416" alt="screenshot 2018-11-23 at 10 47 26" src="https://user-images.githubusercontent.com/40594944/48939760-3f468680-ef0d-11e8-9cab-c7ee6641014a.png">

**Comment by Oliversw** [comment]
We fixed it so that every time the code runs it deletes the previous beers, yay!
